name: "Centos build"
description: "Build Imagemagick RPMs from sources for centos"
outputs:
  built-version:
    description: 'The package version we built'
inputs:
  im-version:
    description: 'The package version we built for imagemagick'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
     IMAGEMAGICK_VERSION: ${{ inputs.im-version }}