name: "Centos build"
description: "Build Imagemagick RPMs from sources for centos"
outputs:
  built-version:
    description: 'The package version we built'
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    - IMAGEMAGICK_VERSION=imagemagick-build/.github/actions/env